version: '3'
services:
  minio:
    image: minio/minio
    restart: always
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: miniosecret
    volumes:
      - .minio/data:/data
      - .minio/metadata:/metadata
    labels:
      - "com.docker.architecture=arm64v8"
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: engynear
      POSTGRES_PASSWORD: 132wersdf
      POSTGRES_DB: blockvault
    volumes:
      - .postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
